name: 'Setup rust corset'
description: 'Install rust and rust corset'
inputs:
  build:
    description: 'Build Corset from Scratch'
    required: false
    default: true
  version:
    # Corresponds to the corset release tag for the desired version.
    description: 'Corset tag to use'
    required: false
    default: 'v9.7.17'
  asset_id:
    # Corresponds to the Github asset id for the asset published as part
    # of the release.  Specifically, it should be the id for the asset
    # "corset_vX.Y.Z_x86_64-unknown-linux-musl.tar.gz" where X.Y.Z is
    # the desired version.  To figure out the asset id, you'll need to
    # access the Github API via e.g. curl --- google it :)
    description: 'Github asset id to use (when downloading)'
    required: false
    default: '203897668'
  github-token:
    description: 'Github token (needed for download)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download Corset
      shell: bash
      if: ${{ inputs.build != 'true' }}
      run: |
        curl -L \
        -H "Accept: application/octet-stream" \
        -H "Authorization: Bearer ${{ inputs.github_token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -o corset.tar.gz \
        https://api.github.com/repos/Consensys/corset/releases/assets/${{ inputs.assert_id }}
        tar xzf corset.tar.gz
        mv corset $HOME

    - name: Install Rust
      if: ${{ inputs.build == 'true' }}
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build & Install Corset
      if: ${{ inputs.build == 'true' }}
      shell: bash
      run: RUSTFLAGS=-Awarnings cargo install --git https://github.com/Consensys/corset.git --tag ${{ inputs.version }} --locked --force
      env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
